services:
  backend:
    # image: node
    build: ./backend
    # environment:
    #   - PORT=5000
    env_file:
      - ./backend/.env
    ports:
      - 8000:5000
  frontend:
    build: ./frontend
    ports:
      - 5173:5173

  redis:
    image: redis
    ports:
      -6379:6379